[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_pgsql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.tokenizer", "composer"]

[phases.install]
cmds = ["cd formfree/laravel-base && composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
  "cd formfree/laravel-base && php artisan config:cache",
  "cd formfree/laravel-base && php artisan route:cache",
  "cd formfree/laravel-base && php artisan view:cache"
]

[start]
cmd = "cd formfree/laravel-base && php artisan serve --host 0.0.0.0 --port $PORT"
